### ISSUE TITLE
[FR] Hide floating TOC on click of heading

### ISSUE THREAD

**Issue by N3C2L** [PKM-er/obsidian-floating-toc-plugin#103]
Thank you for this great plugin.

I love that you could collapse/expand the header with ctrl+click.

The style settings are important and useful.

May I ask if you could introduce a new setting: Hide the floating TOC when a header is clicked?

Advantage would be that I wouldn't need to move the mouse away after I click inside the floating TOC.

What do you think?

**Comment by cumany** [comment]
Idea is very good, but here involves a series of triggering events, processing is not easy, because I am mainly through the css hover event, so after clicking actually your mouse is still in the element and continue to trigger the hover behavior

**Comment by N3C2L** [comment]
Thanks for considering adding this.
I am not aware how to implement this, because I know only a little css and html. But maybe one of this approches can help:
1. Changing the display property on click to hide the floating TOC? 
2. Or maybe spawn another invisible area (only 50ms?) on click over the TOC (when this area spawns, the hover effect over the TOC will be gone)?

Other thing:
I discovered a bug in this settings (also tested in sandbox vault) :

<img width="525" alt="fsdfsdf" src="https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/74585843/bc82d527-0955-4d3b-9061-70b92d74a7b9">


Set this option to 1 and hover the floating toc. Result: The interface shows up immeditaley but the fonts later (1s).
