### ISSUE TITLE
Feature Quest：set deflaut TOC  level

### ISSUE THREAD

**Issue by Masktial** [PKM-er/obsidian-floating-toc-plugin#32]
- Feature Quest：

Set deflaut TOC level in setup menu，and expand TOC when needed，as below.
希望设置中能够选择默认的大纲显示级别，并且在需要时能展开，如下图。
![image](https://user-images.githubusercontent.com/82996431/201249730-1dbd99ab-62dd-4acb-a12f-9d6ea84351cf.png)

- Reason

Sometime TOC is too long, it's easy to active it in accident. It seems limit the height of TOC works too. But it's still hard to find target heading.
缘由是：长文TOC过长，无论放在左侧还是右侧，不小心碰到即误触的频率都很高。限制TOC的显示高度或许也行。但TOC过长也会导致很难找到想要的标题。
![image](https://user-images.githubusercontent.com/82996431/201251757-6ceb5749-3524-4b01-b817-359e9a527a5a.png)

**Comment by cumany** [comment]
2.4.1 已经支持
