### ISSUE TITLE
[FR] add button "Scroll to Bottom"

### ISSUE THREAD

**Issue by ku-zhen** [PKM-er/obsidian-floating-toc-plugin#52]
Amazing plugin！ I know you have the button “Scroll to Top” and it‘s very convinent, but it doesnt have a button "Scroll to Bottom". 
Most of time, I need add someting to the bottom ,or I need to look footnote and others.
I think it useful to everyone, not only for me, thanks.

**Comment by miaoziguan** [comment]
同求

**Comment by FeiLZX3Km** [comment]
相同请求，请求作者添加“一键至底”的功能。

**Comment by cumany** [comment]
2.4.3 已经支持
