### ISSUE TITLE
插件安装后，没有找到插件设置相关的选项

### ISSUE THREAD

**Issue by mdsnalw** [PKM-er/obsidian-floating-toc-plugin#62]
![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/57386018/f357b61b-f9d0-4e66-adbd-455cecfc8abf)

如以下设置和截图，请问如何配置才能打开Floating TOC的插件设置界面？此插件的设置是否在插件的对应Options选项里？

![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/57386018/f9e753d2-b5c8-4c42-bd9b-9b4a887934c3)

参考链接：https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/floating-toc/

**Comment by cumany** [comment]
应该插件文件夹 已经有floating toc 目录了  建议删除旧的目录 重新下载安装插件
