### ISSUE TITLE
[功能请求] 允许用户在大纲中隐藏任意级的标题, 而非仅可以隐藏第一级的标题

### ISSUE THREAD

**Issue by XMB-7** [PKM-er/obsidian-floating-toc-plugin#65]
用例如下, 我经常把后几级的标题(比如说56级标题)设为正文样式, 然后用它们写一些可区域折叠的笔记性质的内容(不用列表或callout来实现折叠, 是其内插入的内容种类与样式有限, 不够灵活). 
但问题是插入的这些都会在大纲中显示出来, 使得大纲极其臃肿, 因此希望能够添加一些功能, 允许用户自设显示任意级的标题.
另外 #53  也有类似需求, 希望酌情考虑增添相应功能, 感谢.

**Comment by cumany** [comment]
新版本已经支持。
