### ISSUE TITLE
请问作者的布局是怎么设置的

### ISSUE THREAD

**Issue by viocha** [PKM-er/obsidian-floating-toc-plugin#73]
非常喜欢作者的Obsidian界面，请问是如何设置布局和工具栏的，用了哪些插件和配置呢？
![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/66580331/4b191258-e0dd-4700-a832-842877bb54e1)

**Comment by cumany** [comment]
editing toolbar  + floating toc
