### ISSUE TITLE
希望可以设置同一层级的文字完全对齐

### ISSUE THREAD

**Issue by DavidJoyDong** [PKM-er/obsidian-floating-toc-plugin#76]
这个插件非常好用，可以取代核心插件 Outline

## 问题描述
eg. 这个是我一篇笔记的大纲（Outline 核心插件的显示效果）

它这个展开三角看起来就还行（不是特别好看，但是文字是对齐的）
![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/47232992/18a65fee-79e0-4eeb-835b-6f41dec005f6)

这是 floating toc 的显示效果，我想表达的问题，就是这个**倒三角**和**圆点**，会干扰同级文字之间的对其，导致不够直观。

![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/47232992/ffbc7509-b212-49c2-b150-38efe4c931fd)

## 解释

我个人觉得这个**倒三角**和**圆点**会动态地影响对其，从而造成干扰。另外我不太清除这个圆点的含义是什么。

用别人的理论来说的话，我觉得这个可以解释？
> 对齐：任何东西都不能在页面上随意安放。每个元素都应当与页面上的另一个元素。有某种视觉联系。这样能建立一种清晰、精巧而且清爽的外观。
出自：The Non-Designer's Design Book，写给大家看的设计书，Robin Williams，苏金国

## 希望
做成开关，方便不同人的使用习惯
- Toggle：给每个标题前面预留出来一个位置专门用来显示倒三角和圆点，让文字始终保持对齐
- Toggle：让每个标题前面对齐地显示层级标签（https://github.com/PKM-er/obsidian-floating-toc-plugin/issues/12#issuecomment-1256973447）
- Toggle：是否显示倒三角和圆点

总之，我觉得能有一个稳定的对齐是比较舒服的

**Comment by cumany** [comment]
感谢指出问题，倒三角代表当前 文章对应的题目的父级，圆点代表 表示当前浏览到哪个标题。 设计问题我需要再考究一下
