### ISSUE TITLE
大神，帮看下这个插件突然不好使了，不知道什么情况

### ISSUE THREAD

**Issue by lyeeo** [PKM-er/obsidian-floating-toc-plugin#80]
用的时候发现不好使了，之前还是可以的
点击设置的目录，没有反应，无法跳转，但是点击，回到最上面是好使的

点击设置的目录无法实现跳转

从新建立了一个新的库，测试，都是可以正常使用的

不知道我的库发生了什么，这个插件是会和其他的插件发生冲突么

有发生过这样的情况么~

**Comment by cumany** [comment]
两个库的插件版本一样吗

**Comment by lyeeo** [comment]
你好，我一个一个排除测试出来了，是一个css文件打开，插件就会不好使
我截图下，大神帮看下 插件可以修改兼容这个css文件么
![Uploading PixPin_2023-12-02_02-20-35.png…]()

**Comment by cumany** [comment]
> .cm-formatting-header{
> display: none;
> }

这个是因为你把编辑器定位用的元素隐藏了 所以无法跳转，解决办法是 不要使用 display none 隐藏元素，使用
.cm-formatting-header{
  visibility：hidden；
  }

**Comment by lyeeo** [comment]
大神，刚替换试了下，编辑模式下点击标题所在的行，您发法代码 无法隐藏 # 这个井号
没事 找到原因就好，我把那个css关闭，如果影响到定位，就不开启隐藏了~~ 谢谢

**Comment by Khande** [comment]
我今天也遇到了这个问题，使用二分法定位问题的插件 [divide-and-conquer](https://github.com/chrisgrieser/obsidian-divide-and-conquer)，发现是 Close Similar Tabs 这个插件导致的，禁用就好了。
