### ISSUE TITLE
干扰表格编辑

### ISSUE THREAD

**Issue by wenbopeng** [PKM-er/obsidian-floating-toc-plugin#84]
![Recording 2023-12-13 163738](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/74350447/85c0ba80-2229-42c9-9abd-ff3793013ed1)

开启插件后, 实时预览模式编辑表格内容, 会导致表格内容跳动

ps.这个问题只出现在目录在左侧的时候. 如果目录在右侧, 则正常

**Comment by jianwu111** [comment]
有同样的问题，开启之后，表格无法正确插入光标
